applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<shortname>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('lista-by-job/<job>/', views.ListByJob.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKWord.as_view()),
    path('listar-habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
    path('success-deleted/', views.SuccessDeletedView.as_view(), name='correcto_borrado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad


class Empleado(models.Model):
    """"Modelo para tabla empleado"""

    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO')
    )
    #Contador
    #Administrador
    #Economista
    #Otro
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombres completos', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField('Avatar', upload_to='empleados', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    def save(self, *args, **kwargs):
        self.full_name = f"{self.first_name} {self.last_name}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Mi empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['first_name']
        unique_together = ('first_name', 'last_name')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/empleados/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# models
from .models import Empleado
# forms
from .forms import EmpleadoForm

# Create your views here.

class InicioView(TemplateView):
    """"Vista que carga la página de inicio"""
    template_name = 'inicio.html'

# 1.- Listar todos los empleados de la empresa
class ListAllEmpleados(ListView):
    """"Lista todos los empleados"""
    template_name = 'empleados/list_all.html'
    paginate_by = 4
    ordering = ['first_name']
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave=self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        print("lista resultado:", lista)
        return lista

# Listar empleados y poder editar o eliminar
class ListaEmpleadosAdmin(ListView):
    """"Lista todos los empleados"""
    template_name = 'empleados/lista_empleados.html'
    paginate_by = 10
    ordering = ['first_name']
    context_object_name = 'empleados'
    model = Empleado

# 2.- Listar todos los empleados que pertenecen a una área de la empresa
class ListByAreaEmpleado(ListView):
    """"Lista empleados de un área"""
    template_name = 'empleados/list_by_area.html'
    context_object_name = 'empleados'

    #queryset = Empleado.objects.filter(
    #    departamento__shortname='contabilidad'
    #)

    def get_queryset(self):
        area=self.kwargs.get('shortname')
        lista =  Empleado.objects.filter(
            departamento__shortname=area
        )
        return lista

# 3.- Listar empleados por trabajo
class ListByJob(ListView):
    """"Lista empleados en un trabajo"""
    template_name = 'empleados/list_by_job.html'

    def get_queryset(self):
        trabajo=self.kwargs.get('job')
        lista = Empleado.objects.filter(
            job=trabajo
        )
        return lista

# 4.- Listar empleados por palabras clave
class ListEmpleadosByKWord(ListView):
    """"Lista empleados por palabra clave"""
    template_name = 'empleados/list_by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print('****************')
        palabra_clave=self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name=palabra_clave
        )
        print("lista resultado:", lista)
        return lista

# 5.- Listar habilidades de un empleado
class ListHabilidadesEmpleado(ListView):
    """"Lista empleados por habilidades"""
    template_name = 'empleados/list_by_habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        #id_empleado= self.request.GET.get('kword', '')
        #id_empleado_int = int(id_empleado)
        empleado = Empleado.objects.get(id=5)
        return empleado.habilidades.all()

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'empleados/detail_empleado.html'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        #Todo un proceso
        context['titulo']='Empleado del mes'
        return context

class SuccessView(TemplateView):
    template_name = 'empleados/success.html'

class EmpleadoCreateView(CreateView):
    template_name = 'empleados/add.html'
    model = Empleado
    form_class = EmpleadoForm

    success_url = reverse_lazy('empleados_app:empleados_admin')

    def form_valid(self, form):
        #Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

class EmpleadoUpdateView(UpdateView):
    template_name = 'empleados/update.html'
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'
    ]
    success_url = reverse_lazy('empleados_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('************Metodo Post*********')
        print(request.POST)
        print(request.POST['last_name'])
        return super(EmpleadoUpdateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        #Logica del proceso
        print('************Metodo Form Valid*********')
        return super(EmpleadoUpdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'empleados/delete.html'
    success_url = reverse_lazy('empleados_app:empleados_admin')

class SuccessDeletedView(TemplateView):
    template_name = 'empleados/success-deleted.html'

templates/empleados/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Registrar empleado
            </h1>
            <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                 <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Área:
                        {{ form.departamento}}
                    </label>
                </div>
                <div class="cell large-12">
                    <label>Habilidades extra:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell large-12">
                    <label>Foto:
                        {{ form.avatar }}
                    </label>
                </div>
                <div class="cell large-12">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/empleados/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Eliminar empleado: {{ object.full_name }}
            </h1>
            <form class="cell" method="POST">{% csrf_token %}
                <div class="callout secondary">
                    <h5>Desea eliminar este empleado</h5>
                    <button type="submit" class="alert button">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/empleados/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ object.full_name }}
{% endblock title %}

{% block content %}
  {% include 'includes/header.html' %}
  <div class="grid-container">
      <div class="grid-x grid-margin-x align-center">
          <h1 class="cell">
              Detalle de un empleado
          </h1>
          <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
              <div class="card-divider">
                {{ empleado.get_job_display }}
              </div>
              {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
              {% else %}
                <img src="{% static 'img/Empleado_Avatar.jpg' %}">
              {% endif %}
              <div class="card-section">
                <h4>{{ empleado.full_name }}</h4>
                <p>Nombres: {{ empleado.first_name }} </p>
                <p>Apellidos: {{ empleado.last_name }} </p>
                <p>Departamento: {{ empleado.departamento.name }} </p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all %}
                        <li>{{ h.habilidad }}</li>
                    {% endfor %}
                </ul>
              </div>
          </div>
      </div>
  </div>
{% endblock content %}

templates/empleados/list_all.html
{% extends 'base.html' %}

{% block title %}
  Listar
{% endblock title %}

{% block content %}
  {% include 'includes/header.html' %}
  <div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">
        Todos los empleados registrados
      </h1>
      <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
        <div class="cell large-7">
          <input type="text" id="kword" name="kword" placeholder="buscar empleado">
        </div>
        <div class="cell large-2">
          <button class="submit success button">Buscar</button>
        </div>
      </form>
      <div class="cell">
        <table>
          <thead>
            <tr>
              <th width="200">ID</th>
              <th>NOMBRES</th>
              <th width="150">APELLIDOS</th>
              <th width="150">DEPARTAMENTO</th>
              <th width="150">ACCION</th>
            </tr>
          </thead>
          <tbody>
            {% for e in empleados%}
            <tr>
              <td>{{ e.id }}</td>
              <td>{{ e.first_name }}</td>
              <td>{{ e.last_name }}</td>
              <td>{{ e.departamento }}</td>
              <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id%}">Ver</a></td>
            </tr>
            {%  endfor %}
          </tbody>
       </table>
      </div>
      <div class="cell">
          {% if is_paginated %}
              <nav aria-label="Pagination">
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">
                                Atrás
                            </a>
                        </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">
                                    You're on page
                                </span>
                                {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pagina }}">
                                    {{ pagina }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">
                                Siguiente
                            </a>
                        </li>
                    {% endif %}
                  </ul>
             </nav>
          {%  endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/empleados/list_by_area.html
{% extends 'base.html' %}

{% block title %}
    Lista empleados por departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista de empleados por departamento</h1>
            <div class="cell">
            <table>
              <thead> 
                <tr>
                  <th width="200">ID</th>
                  <th>NOMBRES</th>
                  <th width="150">APELLIDOS</th>
                  <th width="150">DEPARTAMENTO</th>
                  <th width="150">ACCION</th>
                </tr>
              </thead>
              <tbody>
                {% for e in empleados%}
                <tr>
                  <td>{{ e.id }}</td>
                  <td>{{ e.first_name }}</td>
                  <td>{{ e.last_name }}</td>
                  <td>{{ e.departamento }}</td>
                  <td><a class="button warning" href="{% url 'empleados_app:empleado_detail' e.id%}">Ver</a></td>
                </tr>
                {%  endfor %}
              </tbody>
            </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/empleados/list_by_habilidades.html
<h1>Habilidades de empleado</h1>

<form method="GET">{% csrf_token %}
    <input type="number" id="kword" name="kword" min="1" placeholder="Ingrese el ID del empleado">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    {% for h in habilidades%}
        <li>{{h}}</li>
    {%  endfor %}
</ul>

templates/empleados/list_by_job.html
<h1>Lista empleados por trabajo</h1>

<ul>
    {% for e in object_list%}
        <li>{{e}}</li>
    {%  endfor %}
</ul>

templates/empleados/list_by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    {% for e in empleados%}
        <li>{{e}}</li>
    {%  endfor %}
</ul>

templates/empleados/lista_empleados.html
{% extends 'base.html' %}

{% block title %}
  Listar
{% endblock title %}

{% block content %}
  {% include 'includes/header.html' %}
  <div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">
        Administrar los empleados registrados
      </h1>
      <div class="cell">
        <table>
          <thead>
            <tr>
              <th width="200">ID</th>
              <th>NOMBRES</th>
              <th width="150">APELLIDOS</th>
              <th width="150">DEPARTAMENTO</th>
              <th width="150">ACCION 1</th>
              <th width="150">ACCION 2</th>
            </tr>
          </thead>
          <tbody>
            {% for e in empleados%}
            <tr>
              <td>{{ e.id }}</td>
              <td>{{ e.first_name }}</td>
              <td>{{ e.last_name }}</td>
              <td>{{ e.departamento }}</td>
              <td><a class="button success" href="{% url 'empleados_app:modificar_empleado' e.id %}">Editar</a></td>
              <td><a class="button alert" href="{% url 'empleados_app:eliminar_empleado' e.id %}">Eliminar</a></td>
            </tr>
            {%  endfor %}
          </tbody>
       </table>
      </div>
      <div class="cell">
          {% if is_paginated %}
              <nav aria-label="Pagination">
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">
                                Atrás
                            </a>
                        </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">
                                    You're on page
                                </span>
                                {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pagina }}">
                                    {{ pagina }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">
                                Siguiente
                            </a>
                        </li>
                    {% endif %}
                  </ul>
             </nav>
          {%  endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/empleados/success-deleted.html
<h1>Se borró el empleado seleccionado</h1>

templates/empleados/success.html
<h1>Felicitaciones, se guardó/actualizó correctamente el empleado</h1>

templates/empleados/update.html
{% extends 'base.html' %}

{% block title %}
    Editar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Modificar datos de empleado
            </h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %%}
                    <div class="cell large-6">
                        <label>Nombres:
                            {{ form.first_name }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Apellidos:
                            {{ form.last_name }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Trabajo:
                            {{ form.job }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Área:
                            {{ form.departamento}}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>Habilidades extra::
                            {{ form.habilidades }}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}