applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('lista-by-area/<shortname>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('lista-by-job/<job>/', views.ListByJob.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKWord.as_view()),
    path('listar-habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
    path('success-deleted/', views.SuccessDeletedView.as_view(), name='correcto_borrado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    shortname = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Áreas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shortname')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shortname

applications/departamento/forms.py
from django import forms
from applications.departamento.models import Departamento

class NewDepartamentoForm(forms.Form):
    nombres = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .forms import NewDepartamentoForm
from applications.empleados.models import Empleado, Habilidades
from .models import Departamento
from django.urls import reverse_lazy

# Create your views here.
class DepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    model = Departamento
    context_object_name = 'departamentos'

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('departamento_app:departamento_list')

    def form_valid(self, form):
        print("**********Estamos en el form valid***************")
        # Crear y guardar departamento. Mediante una forma
        depa = Departamento(name=form.cleaned_data['departamento'], shortname=form.cleaned_data['shortname'])
        depa.save()
        # Crear y guardar empleado. Mediante otra forma
        nombres = form.cleaned_data['nombres']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(first_name=nombres, last_name=apellidos, job=1, departamento=depa)
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista de departamentos
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista de Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in  departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shortname }}</td>
                            <td>
                                <a class="button warning" href="{% url 'empleados_app:empleados_area' departamento.shortname %}">Ver empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar departamento
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Registrar departamento
            </h1>
            <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
                 <h3 class="cell">
                    Datos del empleado
                 </h3>
                 <div class="cell large-6">
                    <label>Nombres:
                        {{ form.nombres }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.apellidos }}
                    </label>
                </div>
                <h3 class="cell">
                    Datos del departamento
                </h3>
                 <div class="cell large-6">
                    <label>Departamento:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Nombre corto:
                        {{ form.shortname }}
                    </label>
                </div>
                <div class="cell large-12">
                    <button type="submit" class="button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}